name: Update PR Description
on:
  pull_request:
    types: [opened, edited]

jobs:
  update_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Payload Debugging
        uses: actions/github-script@v5
        with:
          script: |
            echo "${{ toJson(github.event) }}"
            echo "${{ toJson(context.repo) }}"

      - name: Update PR Description
        uses: actions/github-script@v5
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const updatedDescription = pullRequest.body + '\n Some additional text.';

            // use regex? no need for sed because we're already in javascript
            // don't need portability of sed:
            // - lower requirements to run
            // - requires *less* to run/ increases performance

            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              number: context.payload.pull_request.number,
              body: updatedDescription,
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
